# Generated by Django 5.1.4 on 2025-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rekodimatumizi_fromshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfuel',
            name='saprice',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
