# Generated by Django 5.1.4 on 2025-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transferfuel_saprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfuel',
            name='FuelAmo',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
