# Generated by Django 5.1.4 on 2025-02-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_transferfuel_fuelamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodimatumizi',
            name='Fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuel'),
        ),
    ]
