# Generated by Django 5.1.4 on 2025-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rekodimatumizi_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpump',
            name='qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
