# Generated by Django 5.1.4 on 2025-03-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_shiftpump_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='puprice',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='saprice',
        ),
        migrations.AddField(
            model_name='shiftpump',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shiftpump',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shiftpump',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shifts',
            name='lossprof',
            field=models.BooleanField(default=False),
        ),
    ]
