# Generated by Django 5.1.4 on 2025-03-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_shifts_puprice_remove_shifts_saprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiftsTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftName', models.CharField(max_length=100, null=True)),
                ('shFrom', models.TimeField()),
                ('shTo', models.TimeField()),
                ('Interprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise')),
            ],
        ),
    ]
