# Generated by Django 5.1.4 on 2025-03-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_shiftstime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftstime',
            old_name='shiftName',
            new_name='name',
        ),
    ]
