# Generated by Django 5.1.4 on 2025-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_shiftname_shiftstime_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftstime',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
