# Generated by Django 5.1.4 on 2025-04-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_shiftstime_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiftSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('complete', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shiftstime')),
            ],
        ),
        migrations.AddField(
            model_name='shifts',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shiftsesion'),
        ),
    ]
