# Generated by Django 5.1.4 on 2025-04-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_shiftsesion_shifts_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfuel',
            name='readA',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transferfuel',
            name='readB',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
