# Generated by Django 5.1.4 on 2025-04-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_transferfuel_reada_transferfuel_readb'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shiftsesion'),
        ),
    ]
