# Generated by Django 5.1.4 on 2025-04-15 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_attachments_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuelPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bprice', models.DecimalField(decimal_places=4, max_digits=20)),
                ('Aprice', models.DecimalField(decimal_places=4, max_digits=20)),
                ('date', models.DateField()),
                ('fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel')),
            ],
        ),
    ]
