# Generated by Django 5.1.4 on 2025-04-15 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_fuelpricechange'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricechange',
            name='Interprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise'),
        ),
    ]
