# Generated by Django 5.1.4 on 2025-04-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_fuelpricechange_interprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='pumpTemper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRead', models.DecimalField(decimal_places=4, max_digits=20)),
                ('ARead', models.DecimalField(decimal_places=4, max_digits=20)),
                ('desc', models.TextField(blank=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprisepermissions')),
                ('pump', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuel_pumps')),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuelpricechange')),
                ('usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend')),
                ('temper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.pumptemper')),
            ],
        ),
    ]
