# Generated by Django 5.1.4 on 2025-04-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_pumptemper_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricechange',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fuelpricechange',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
