# Generated by Django 5.1.4 on 2025-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_fuelpricechange_desc_alter_fuelpricechange_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
