# Generated by Django 5.1.4 on 2025-04-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_notifications_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpricechange',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend'),
        ),
    ]
