# Generated by Django 5.1.4 on 2025-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_fuelpricechange_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='darkMode',
            field=models.BooleanField(default=False),
        ),
    ]
