# Generated by Django 5.1.4 on 2025-04-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_userextend_darkmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='darkmode',
        ),
    ]
