# Generated by Django 5.1.4 on 2025-04-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_remove_userextend_darkmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumptemper',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
