# Generated by Django 5.1.4 on 2025-05-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_pumptemper_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjustments',
            name='final',
        ),
        migrations.RemoveField(
            model_name='adjustments',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='adjustments',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='adjustments',
            name='tank',
        ),
        migrations.AddField(
            model_name='adjustments',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shiftsesion'),
        ),
        migrations.CreateModel(
            name='tankAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('stick', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('diff', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel_tanks')),
            ],
        ),
    ]
