# Generated by Django 5.1.4 on 2025-05-04 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_remove_adjustments_final_remove_adjustments_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankadjust',
            name='adj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.adjustments'),
        ),
    ]
