# Generated by Django 5.1.4 on 2025-05-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_tankadjust_adj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recevefuel',
            name='From',
        ),
        migrations.RemoveField(
            model_name='recevefuel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='recevefuel',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='recevefuel',
            name='receive',
        ),
        migrations.CreateModel(
            name='receivedFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transfer_from')),
                ('Fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel')),
                ('To', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel_tanks')),
                ('receive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.recevefuel')),
            ],
        ),
    ]
