# Generated by Django 5.1.4 on 2025-05-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_recevefuel_from_remove_recevefuel_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='ses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shiftsesion'),
        ),
    ]
