# Generated by Django 5.1.4 on 2025-05-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_recevefuel_ses'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='Invo_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adjustments',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
