# Generated by Django 5.1.4 on 2025-05-11 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_adjustments_invo_no_adjustments_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tankcontainer'),
        ),
    ]
