# Generated by Django 5.1.4 on 2025-05-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_adjustments_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='Interprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.interprise'),
        ),
    ]
