# Generated by Django 5.1.4 on 2025-05-11 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_adjustments_interprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextend'),
        ),
    ]
