# Generated by Django 5.1.4 on 2025-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_adjustments_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='adj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.adjustments'),
        ),
    ]
