# Generated by Django 5.1.4 on 2025-05-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_attachments_adj'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankadjust',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
