# Generated by Django 5.1.4 on 2025-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_tankadjust_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='tankSup',
            field=models.BooleanField(default=False),
        ),
    ]
