# Generated by Django 5.1.4 on 2025-05-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_userextend_tanksup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferfuel',
            name='From',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='FuelAmo',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='qty_sales',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='qty_trans',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='qty_used',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='readA',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='readB',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='saprice',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='transferfuel',
            name='to',
        ),
        migrations.CreateModel(
            name='tr_supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextend')),
            ],
        ),
        migrations.AddField(
            model_name='transferfuel',
            name='trSup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tr_supervisor'),
        ),
        migrations.CreateModel(
            name='transFromTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('saprice', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('FuelAmo', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty_trans', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty_sales', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty_used', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('closed', models.BooleanField(default=False)),
                ('From', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transfer_from')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shiftpump')),
                ('to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel_tanks')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transferfuel')),
            ],
        ),
    ]
