# Generated by Django 5.1.4 on 2025-05-27 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_remove_transferfuel_from_remove_transferfuel_fuelamo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfromto',
            name='pump',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel_pumps'),
        ),
    ]
