# Generated by Django 5.1.4 on 2025-05-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_transfromto_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfuel',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tankcontainer'),
        ),
        migrations.AddField(
            model_name='transferfuel',
            name='otherCont',
            field=models.TextField(blank=True),
        ),
    ]
