# Generated by Django 5.1.4 on 2025-05-30 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_transferfuel_container_transferfuel_othercont'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferfuel',
            name='recDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transfromto',
            name='Fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel'),
        ),
    ]
