# Generated by Django 5.1.4 on 2025-06-08 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_transferfuel_recdate_transfromto_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankcontainer',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend'),
        ),
    ]
