# Generated by Django 5.1.4 on 2025-06-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_tankcontainer_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfromto',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.transferfuel'),
        ),
    ]
