# Generated by Django 5.1.4 on 2025-06-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_transfromto_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_tanks',
            name='minm',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
