# Generated by Django 5.1.4 on 2025-06-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_fuel_tanks_minm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfromto',
            name='qty_sales',
        ),
        migrations.RemoveField(
            model_name='transfromto',
            name='qty_trans',
        ),
        migrations.RemoveField(
            model_name='transfromto',
            name='qty_used',
        ),
        migrations.AddField(
            model_name='transfromto',
            name='taken',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
