# Generated by Django 5.1.4 on 2025-06-20 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_remove_transfromto_qty_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfuel',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receivedfuel',
            name='qtyA',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='receivedfuel',
            name='qtyB',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='recevefuel',
            name='Fromcont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tankcontainer'),
        ),
        migrations.CreateModel(
            name='ToContena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tankcontainer')),
            ],
        ),
        migrations.AddField(
            model_name='recevefuel',
            name='Tocont',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tocontena'),
        ),
    ]
