# Generated by Django 5.1.4 on 2025-06-20 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_receivedfuel_price_receivedfuel_qtya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='FromTransf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transferfuel'),
        ),
    ]
