# Generated by Django 5.1.4 on 2025-06-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_recevefuel_fromtransf'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='recDate',
            field=models.DateTimeField(null=True),
        ),
    ]
