# Generated by Django 5.1.4 on 2025-06-23 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0045_recevefuel_recdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='Incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextend'),
        ),
        migrations.AddField(
            model_name='tocontena',
            name='Incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextend'),
        ),
        migrations.AlterField(
            model_name='recevefuel',
            name='op',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.tr_supervisor'),
        ),
    ]
