# Generated by Django 5.1.4 on 2025-06-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_recevefuel_incharge_tocontena_incharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='saleOnReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('ses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shiftsesion')),
                ('tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuel_tanks')),
            ],
        ),
    ]
