# Generated by Django 5.1.4 on 2025-06-23 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_saleonreceive'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleonreceive',
            name='receive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.receivedfuel'),
        ),
    ]
