# Generated by Django 5.1.4 on 2025-06-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_saleonreceive_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustments',
            name='receive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.recevefuel'),
        ),
    ]
