# Generated by Django 5.1.4 on 2025-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0049_adjustments_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
