# Generated by Django 5.1.4 on 2025-06-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0050_recevefuel_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('Invo_no', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('recDate', models.DateTimeField(null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('payed', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('record_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.interprisepermissions')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.wasambazaji')),
            ],
        ),
        migrations.CreateModel(
            name='PuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('Fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.fuel')),
                ('pu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.purchases')),
            ],
        ),
    ]
