# Generated by Django 5.1.4 on 2025-06-29 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_purchases_pulist'),
    ]

    operations = [
        migrations.AddField(
            model_name='recevefuel',
            name='FromPurchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.purchases'),
        ),
    ]
