# Generated by Django 5.1.4 on 2025-06-29 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_recevefuel_frompurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='record_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userextend'),
        ),
    ]
