# Generated by Django 5.1.4 on 2025-06-30 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_alter_purchases_record_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.purchases'),
        ),
    ]
