# Generated by Django 5.1.4 on 2025-06-30 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_attachments_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toacash',
            name='pu',
        ),
        migrations.AddField(
            model_name='toacash',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.purchases'),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='Interprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise'),
        ),
    ]
