# Generated by Django 5.1.4 on 2025-07-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_remove_toacash_pu_toacash_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toacash',
            name='oda_fidia',
        ),
        migrations.RemoveField(
            model_name='toacash',
            name='prdxn',
        ),
        migrations.RemoveField(
            model_name='toacash',
            name='sale_fidia',
        ),
        migrations.AlterField(
            model_name='toacash',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.wasambazaji'),
        ),
    ]
