# Generated by Django 5.1.4 on 2025-07-02 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_remove_toacash_oda_fidia_remove_toacash_prdxn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='Interprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise'),
        ),
    ]
