# Generated by Django 5.1.4 on 2025-07-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0057_alter_rekodimatumizi_interprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulist',
            name='rcvd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
    ]
