# Generated by Django 5.1.4 on 2025-07-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_pulist_rcvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='depends',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='last_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='period_type',
            field=models.IntegerField(default=0),
        ),
    ]
