# Generated by Django 5.1.4 on 2025-07-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_matumizi_amount_matumizi_depends_matumizi_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='next_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
