# Generated by Django 5.1.4 on 2025-07-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0060_matumizi_next_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='shell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise'),
        ),
    ]
