# Generated by Django 5.1.4 on 2025-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_matumizi_general_matumizi_shell'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
