# Generated by Django 5.1.4 on 2025-07-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_purchases_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='status',
            new_name='closed',
        ),
    ]
