# Generated by Django 5.1.4 on 2025-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_rename_status_purchases_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='ref',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
