# Generated by Django 5.1.4 on 2025-07-19 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_purchases_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsales',
            name='saleFr_shift',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='Invo_no',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='by',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='code',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='cost_sold',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='qty_sold',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='sa_price',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='sa_price_og',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='tank',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='tankIncharge',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='theFuel',
        ),
        migrations.RemoveField(
            model_name='fuelsales',
            name='vihecle',
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shiftsesion'),
        ),
        migrations.CreateModel(
            name='saleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sold', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cost_sold', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sa_price', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sa_price_og', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuelsales')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shiftpump')),
                ('tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuel_tanks')),
                ('theFuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuel')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale_From_shifts',
        ),
    ]
