# Generated by Django 5.1.4 on 2025-07-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_remove_fuelsales_salefr_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='Invo_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprisepermissions'),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='contInchage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend'),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wateja'),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='driver',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='payed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='vihecle',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
