# Generated by Django 5.1.4 on 2025-07-19 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_fuelsales_invo_no_fuelsales_amount_fuelsales_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='cont',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.tankcontainer'),
        ),
    ]
