# Generated by Django 5.1.4 on 2025-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_fuelsales_cont'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='isShisft',
            field=models.BooleanField(default=False),
        ),
    ]
