# Generated by Django 5.1.4 on 2025-07-19 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_fuelsales_isshisft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsales',
            name='isShisft',
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='shiftBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.shifts'),
        ),
    ]
