# Generated by Django 5.1.4 on 2025-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_remove_fuelsales_isshisft_fuelsales_shiftby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelsales',
            name='due_date',
        ),
        migrations.AddField(
            model_name='fuelsales',
            name='recDate',
            field=models.DateTimeField(null=True),
        ),
    ]
