# Generated by Django 5.1.4 on 2025-07-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_remove_fuelsales_due_date_fuelsales_recdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='pu',
            field=models.BooleanField(default=False),
        ),
    ]
