# Generated by Django 5.1.4 on 2025-08-14 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0071_userextend_pu'),
    ]

    operations = [
        migrations.AddField(
            model_name='wekacash',
            name='tDebt',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='tTnvo',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CustmDebtPayRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Debt', models.DecimalField(decimal_places=4, max_digits=20)),
                ('Apay', models.DecimalField(decimal_places=4, max_digits=20)),
                ('pay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wekacash')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.fuelsales')),
            ],
        ),
    ]
