# Generated by Django 5.1.4 on 2025-08-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_wekacash_tdebt_wekacash_ttnvo_custmdebtpayrec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wekacash',
            old_name='tTnvo',
            new_name='tInvo',
        ),
    ]
