# Generated by Django 5.1.4 on 2025-08-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0073_rename_ttnvo_wekacash_tinvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='wekacash',
            name='saRec',
            field=models.BooleanField(default=False),
        ),
    ]
