# Generated by Django 5.1.4 on 2025-08-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_wekacash_sarec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wekacash',
            name='Akaunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.paymentakaunts'),
        ),
    ]
