# Generated by Django 5.1.4 on 2025-09-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_alter_wekacash_akaunt'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
