# Generated by Django 5.1.4 on 2025-09-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankadjust',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.fuel'),
        ),
    ]
