# Generated by Django 5.1.4 on 2025-09-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_tankadjust_fuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
