# Generated by Django 5.1.4 on 2025-10-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0078_company_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmdebtpayrec',
            name='Apay',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='custmdebtpayrec',
            name='Debt',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_pumps',
            name='readings',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_tanks',
            name='cost',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_tanks',
            name='maxm',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_tanks',
            name='minm',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_tanks',
            name='price',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuel_tanks',
            name='qty',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuelpricechange',
            name='Aprice',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuelpricechange',
            name='Bprice',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuelsales',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fuelsales',
            name='payed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='matumizi',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pulist',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pulist',
            name='qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pulist',
            name='rcvd',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pumptemper',
            name='ARead',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pumptemper',
            name='BRead',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='payed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivedfuel',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivedfuel',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivedfuel',
            name='qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivedfuel',
            name='qtyA',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivedfuel',
            name='qtyB',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receivefromtr',
            name='rc_qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='fuel_price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='fuel_qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='ilolipwa',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='kiasi',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salelist',
            name='cost_sold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salelist',
            name='qty_sold',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salelist',
            name='sa_price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='salelist',
            name='sa_price_og',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleonreceive',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='saleonreceive',
            name='qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='final',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='initial',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shiftpump',
            name='qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='paid',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tankadjust',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tankadjust',
            name='diff',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tankadjust',
            name='price',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tankadjust',
            name='read',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='tankadjust',
            name='stick',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='After',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='Amount',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='toacash',
            name='before',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfromto',
            name='FuelAmo',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfromto',
            name='cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfromto',
            name='qty',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfromto',
            name='saprice',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transfromto',
            name='taken',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='After',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='Amount',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='before',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wekacash',
            name='tDebt',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
