# Generated by Django 5.1.4 on 2025-10-14 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_alter_custmdebtpayrec_apay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditDebtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('paid', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('code', models.CharField(max_length=20, null=True)),
                ('Invo_no', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wateja')),
            ],
        ),
        migrations.AddField(
            model_name='attachments',
            name='cdOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.creditdebtorder'),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='cdOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.creditdebtorder'),
        ),
    ]
