# Generated by Django 5.1.4 on 2025-10-14 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_creditdebtorder_attachments_cdorder_wekacash_cdorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebtorder',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprisepermissions'),
        ),
    ]
