# Generated by Django 5.1.4 on 2025-10-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_creditdebtorder_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditdebtorder',
            name='consumed',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='creditdebtorder',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
