# Generated by Django 5.1.4 on 2025-10-14 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_creditdebtorder_consumed_creditdebtorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='cdorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.creditdebtorder'),
        ),
    ]
