# Generated by Django 5.1.4 on 2025-10-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_fuelsales_cdorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateja',
            name='limited_order',
            field=models.BooleanField(default=False),
        ),
    ]
