# Generated by Django 5.1.4 on 2025-10-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_wateja_limited_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='mafuta',
            field=models.BooleanField(default=False),
        ),
    ]
