# Generated by Django 5.1.4 on 2025-10-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_matumizi_mafuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='cust',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='exp',
            field=models.BooleanField(default=False),
        ),
    ]
