# Generated by Django 5.1.4 on 2025-11-08 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0086_userextend_cust_userextend_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='cust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wateja'),
        ),
    ]
