# Generated by Django 5.1.4 on 2025-11-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_attachments_cust'),
    ]

    operations = [
        migrations.AddField(
            model_name='wekacash',
            name='used_amount',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
