# Generated by Django 5.1.4 on 2025-11-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_wekacash_used_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateja',
            name='debt_limit',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
