# Generated by Django 5.1.4 on 2025-11-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0089_wateja_debt_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateja',
            name='prepaid_order',
            field=models.BooleanField(default=False),
        ),
    ]
