# Generated by Django 5.1.4 on 2025-11-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_wateja_prepaid_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wateja',
            name='prepaid_order',
        ),
        migrations.AddField(
            model_name='creditdebtorder',
            name='prepaid_order',
            field=models.BooleanField(default=False),
        ),
    ]
