# Generated by Django 5.1.4 on 2025-12-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_remove_wateja_prepaid_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='mobile_pay',
            field=models.BooleanField(default=False),
        ),
    ]
