# Generated by Django 5.1.4 on 2025-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_fuelsales_mobile_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelsales',
            name='customer_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
