# Generated by Django 5.1.4 on 2025-12-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0093_fuelsales_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='toacash',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wekacash',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
