# Generated by Django 5.1.4 on 2026-01-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_toacash_admin_approval_wekacash_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateja',
            name='toIgnore',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
