# Generated by Django 5.1.4 on 2026-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_wateja_toignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentakaunts',
            name='no_amount',
            field=models.BooleanField(default=True),
        ),
    ]
