# Generated by Django 5.1.4 on 2026-01-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0096_paymentakaunts_no_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='acc_supv',
            field=models.BooleanField(default=False),
        ),
    ]
