# Generated by Django 5.1.4 on 2026-01-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_userextend_acc_supv'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentakaunts',
            name='supv_acc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentakaunts',
            name='no_amount',
            field=models.BooleanField(default=False),
        ),
    ]
