# Generated by Django 5.1.4 on 2026-01-19 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0098_paymentakaunts_supv_acc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Akaunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.paymentakaunts')),
            ],
        ),
        migrations.AddField(
            model_name='toacash',
            name='depoTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.depositto'),
        ),
    ]
