# Generated by Django 5.1.4 on 2026-01-19 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_depositto_toacash_depoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositto',
            name='Akaunt',
        ),
        migrations.AddField(
            model_name='depositto',
            name='supv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend'),
        ),
        migrations.AddField(
            model_name='depositto',
            name='weka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.wekacash'),
        ),
    ]
