# Generated by Django 5.1.4 on 2026-01-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_remove_depositto_akaunt_depositto_supv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toacash',
            name='makato',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
