# Generated by Django 5.1.4 on 2026-02-05 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_alter_toacash_makato'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulist',
            name='driver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pulist',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=6)),
                ('simu1', models.CharField(max_length=15)),
                ('simu2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=False)),
                ('compan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.AddField(
            model_name='pulist',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transporter'),
        ),
    ]
