# Generated by Django 5.1.4 on 2026-02-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0102_pulist_driver_pulist_vehicle_transporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporter',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wasambazaji',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
