# Generated by Django 5.1.4 on 2026-02-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_alter_transporter_active_alter_wasambazaji_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pulist',
            old_name='transporter',
            new_name='transp',
        ),
        migrations.AddField(
            model_name='pulist',
            name='trn_amo',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pulist',
            name='trn_paid',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
    ]
