# Generated by Django 6.0.2 on 2026-03-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_rename_transporter_pulist_transp_pulist_trn_amo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulist',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='pulist',
            name='transp',
        ),
        migrations.RemoveField(
            model_name='pulist',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='attachments',
            name='expAttach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.rekodimatumizi'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='puInvo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachments',
            name='receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='attachReceipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rekodimatumizi',
            name='attachReceipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='labor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='tin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wateja',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='exptaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('rate', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
            ],
        ),
        migrations.AddField(
            model_name='matumizi',
            name='taxGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.exptaxgroup'),
        ),
        migrations.CreateModel(
            name='puAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vihecle', models.CharField(blank=True, max_length=500)),
                ('driver', models.CharField(blank=True, max_length=500)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.purchases')),
                ('transp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.transporter')),
            ],
        ),
        migrations.AddField(
            model_name='attachments',
            name='puAttach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.puattachments'),
        ),
        migrations.AddField(
            model_name='pulist',
            name='puAttach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.puattachments'),
        ),
    ]
