# Generated by Django 6.0.2 on 2026-03-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_remove_pulist_driver_remove_pulist_transp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprisepermissions',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
