# Generated by Django 6.0.2 on 2026-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0106_interprisepermissions_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='manunuzi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='posho',
            field=models.BooleanField(default=False),
        ),
    ]
