# Generated by Django 6.0.2 on 2026-03-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_matumizi_manunuzi_matumizi_posho'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='bili',
            field=models.BooleanField(default=False),
        ),
    ]
