# Generated by Django 6.0.2 on 2026-03-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0108_matumizi_bili'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='monthly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='yearly',
            field=models.BooleanField(default=False),
        ),
    ]
