# Generated by Django 6.0.2 on 2026-03-25 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_matumizi_daily_matumizi_monthly_matumizi_weekly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matumizi',
            name='owner',
        ),
    ]
