# Generated by Django 6.0.2 on 2026-03-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_remove_matumizi_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='heo_pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userextend'),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='paye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matumizi',
            name='sta_pay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sta_pay', to='account.interprisepermissions'),
        ),
    ]
