# Generated by Django 6.0.2 on 2026-03-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0111_matumizi_heo_pay_matumizi_paye_matumizi_sta_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='compani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company'),
        ),
    ]
