# Generated by Django 6.0.2 on 2026-03-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0112_matumizi_compani'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matumizi',
            name='period_type',
        ),
        migrations.AddField(
            model_name='matumizi',
            name='Isactive',
            field=models.BooleanField(default=True),
        ),
    ]
