# Generated by Django 6.0.2 on 2026-03-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0113_remove_matumizi_period_type_matumizi_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='party_time',
            field=models.BooleanField(default=False),
        ),
    ]
