# Generated by Django 6.0.2 on 2026-03-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0114_userextend_party_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='payee',
            field=models.BooleanField(default=False),
        ),
    ]
