# Generated by Django 6.0.2 on 2026-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0115_userextend_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='finance',
            field=models.BooleanField(default=False),
        ),
    ]
