# Generated by Django 6.0.2 on 2026-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_userextend_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextend',
            name='male',
            field=models.BooleanField(default=False),
        ),
    ]
