# Generated by Django 6.0.2 on 2026-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0117_userextend_female_userextend_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='nin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
