# Generated by Django 6.0.2 on 2026-04-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0118_userextend_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='kopesheka',
            field=models.BooleanField(default=False),
        ),
    ]
