# Generated by Django 6.0.2 on 2026-04-13 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0119_userextend_kopesheka'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('salary_deduction', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('paid_amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_loan_recorded_by', to='account.userextend')),
                ('compani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.company')),
                ('shell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.interprise')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_loans', to='account.userextend')),
            ],
        ),
        migrations.AddField(
            model_name='wekacash',
            name='loan_pay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.staffloan'),
        ),
    ]
