# Generated by Django 6.0.2 on 2026-04-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0120_staffloan_wekacash_loan_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodimatumizi',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_staff_matumizi', to='account.userextend'),
        ),
        migrations.AddField(
            model_name='rekodimatumizi',
            name='tin_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rekodimatumizi',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rekodi_by', to='account.userextend'),
        ),
    ]
