# Generated by Django 6.0.2 on 2026-04-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_rekodimatumizi_staff_rekodimatumizi_tin_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodimatumizi',
            name='salary_advance',
            field=models.BooleanField(default=False),
        ),
    ]
