# Generated by Django 6.0.2 on 2026-04-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0122_rekodimatumizi_salary_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekodimatumizi',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rekodimatumizi',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.exptaxgroup'),
        ),
    ]
