# Generated by Django 6.0.2 on 2026-04-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0123_rekodimatumizi_admin_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matumizi',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
