# Generated by Django 6.0.2 on 2026-05-01 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0124_matumizi_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanPayMent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='account.staffloan')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.rekodimatumizi')),
            ],
        ),
    ]
