# Generated by Django 6.0.2 on 2026-06-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0126_toacash_trsp_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedfuel',
            name='adminAproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tankadjust',
            name='adminAproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transfromto',
            name='adminAproval',
            field=models.BooleanField(default=False),
        ),
    ]
