# Generated by Django 6.0.2 on 2026-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0127_receivedfuel_adminaproval_tankadjust_adminaproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel_pumps',
            name='analog_readings',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='shiftpump',
            name='analog_used',
            field=models.BooleanField(default=False),
        ),
    ]
