# Generated by Django 6.0.2 on 2026-06-25 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0128_fuel_pumps_analog_readings_shiftpump_analog_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='analog_readings_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shiftpump'),
        ),
    ]
