from django.urls import path

from . import views

urlpatterns=[
   
        path('customers',views.customers, name='customers'),
        path('ViewCustomer',views.ViewCustomer, name='ViewCustomer'),
        path('addcustomer',views.addcustomer, name='addcustomer'),
        path('vendors',views.vendors, name='vendors'),
        path('addvendor',views.addvendor, name='addvendor'),
        path('fuel',views.fuell, name='fuel'),
        path('addTank',views.addTank, name='addTank'),
        path('pumps',views.pumps, name='pumps'),
        path('addpump',views.addpump, name='addpump'),
        path('startshift',views.startshift, name='startshift'),
        path('endshift',views.endshift, name='endshift'),
        path('fueltranfer',views.fueltranfer, name='fueltranfer'),
        path('fueltransfer',views.fueltransfer, name='fueltransfer'),
        path('viewTransfer',views.viewTransfer, name='viewTransfer'),
        path('addAttach',views.addAttach, name='addAttach'),
        path('getTr',views.getTr, name='getTr'),
        path('saveReceive',views.saveReceive, name='saveReceive'),
        path('fuelreceives',views.fuelreceives, name='fuelreceives'),
        path('viewFuelReceive',views.viewFuelReceive, name='viewFuelReceive'),
        path('fuelsales',views.fuelsales, name='fuelsales'),
        path('soldFuel',views.soldFuel, name='soldFuel'),
        path('viewFuelSales',views.viewFuelSales, name='viewFuelSales'),
        path('lipaInvo',views.lipaInvo, name='lipaInvo'),
        path('get_shift_data',views.get_shift_data, name='get_shift_data'),
        path('theshifts',views.theshifts, name='theshifts'),
        path('viewShift',views.viewShift, name='viewShift'),
        path('cashOut',views.cashOut, name='cashOut'),
        path('theshiftsAttend',views.theshiftsAttend, name='theshiftsAttend'),
        path('StartEndShift',views.StartEndShift, name='StartEndShift'),
        path('theshiftsTime',views.theshiftsTime, name='theshiftsTime'),
        path('addSession',views.addSession, name='addSession'),
        path('shiftsDate',views.shiftsDate, name='shiftsDate'),
        path('SessionView',views.SessionView, name='SessionView'),
        path('changePrice',views.changePrice, name='changePrice'),
        path('pumpSetting',views.pumpSetting, name='pumpSetting'),
        path('TankAdjst',views.TankAdjst, name='TankAdjst'),
        path('theAdjst',views.theAdjst, name='theAdjst'),
        path('adjView',views.adjView, name='adjView'),
        path('savaAdjst',views.savaAdjst, name='savaAdjst'),
        path('FuelTrans',views.FuelTrans, name='FuelTrans'),
        path('getStationData',views.getStationData, name='getStationData'),
        path('FuelReceive',views.FuelReceive, name='FuelReceive'),
        path('trucks',views.trucks, name='trucks'),
        path('truckView',views.truckView, name='truckView'),
        path('ChangeTruckIncharge',views.ChangeTruckIncharge, name='ChangeTruckIncharge'),
        path('viewVendor',views.viewVendor, name='viewVendor'),
        path('addPurchase',views.addPurchase, name='addPurchase'),
        path('viewPurchase',views.viewPurchase, name='viewPurchase'),
        path('puchases',views.puchases, name='puchases'),
        path('lipaBill',views.lipaBill, name='lipaBill'),
        path('puReceive',views.puReceive, name='puReceive'),
        path('puClosed',views.puClosed, name='puClosed'),
        path('search_records',views.search_records, name='search_records'),
        path('save_credit_order',views.save_credit_order, name='save_credit_order'),
        path('LimitOrderSet',views.LimitOrderSet, name='LimitOrderSet'),
        path('deleteShiftExpenses',views.deleteShiftExpenses, name='deleteShiftExpenses'),
        path('deleteShift',views.deleteShift, name='deleteShift'),
     

]